/**
 * The favicon — the site's own brand mark, generated rather than drawn by hand.
 *
 * The header already carries a mark: three bars, espresso at the edges and rose in the middle,
 * tallest in the centre. The icon is that same mark on the footer's dark ground, so a tab says
 * the same thing the page says instead of showing a letter a tool picked.
 *
 * Its colours are read out of the stylesheet tokens rather than copied here, because the
 * stylesheet is where they are owned: change `--rose` in 01-tokens.css and `npm run favicon`
 * follows it, with the build refusing to pass until it does. The geometry is that mark measured
 * to the icon's box, so the two cannot quietly disagree about the shape.
 */
import { readFileSync } from 'node:fs';
import { site } from './data.js';

const TOKENS_FILE = 'src/styles/01-tokens.css';

/** Where the icon is published, site-root relative. One spelling, shared by the generator, the
    build guard, and the page's own <link rel="icon">. */
export const FAVICON_FILE = 'assets/favicon.svg';

/**
 * The only colours the mark may use, in the order it uses them: the ground it sits on, the two
 * outer bars, and the middle bar. Read from the tokens rather than named as hex here — this
 * list is the shape of the palette, not the palette.
 */
export const FAVICON_TOKENS = ['espresso', 'ivory', 'rose'];

/**
 * `--name: #hex` out of the token partial. A token that is not a plain hex is an error rather
 * than something to guess at: an icon drawn in a colour the site does not use is worse than a
 * build that stops and says which token moved.
 */
export const readPalette = (tokens = readFileSync(TOKENS_FILE, 'utf8')) => Object.fromEntries(
  FAVICON_TOKENS.map(name => {
    const match = tokens.match(new RegExp(`--${name}:\\s*(#[0-9a-fA-F]{6})\\s*;`));
    if (!match) {
      throw new Error(`${TOKENS_FILE} declares no --${name} as a plain hex colour, so the favicon cannot be generated from it`);
    }
    return [name, match[1].toLowerCase()];
  }),
);

/*
 * The header mark is a 28-unit box: three bars 7 wide, 2 apart, 14 / 25 / 19 tall, flush to the
 * bottom, with the 5px top radius that a 7px-wide bar clamps to a half-round top and a 1px base
 * radius. These are that box at 2x inside a 64-unit canvas, so the proportions are the mark's
 * rather than numbers invented for the icon.
 */
const BAR_WIDTH = 14;
const BAR_GAP = 4;
const BAR_HEIGHTS = [28, 50, 38];
const BAR_TOKENS = ['ivory', 'rose', 'ivory'];
const TOP_RADIUS = BAR_WIDTH / 2;
const BASE_RADIUS = 2;
const MARK_LEFT = 4;
const MARK_SIZE = 56;
const MARK_BOTTOM = MARK_LEFT + MARK_SIZE;

/** The mark's bars, laid out across the canvas and bottom-aligned as the header lays them out. */
const bars = palette => {
  const span = BAR_HEIGHTS.length * BAR_WIDTH + (BAR_HEIGHTS.length - 1) * BAR_GAP;
  const left = MARK_LEFT + (MARK_SIZE - span) / 2;
  return BAR_HEIGHTS.map((height, index) => {
    const x = left + index * (BAR_WIDTH + BAR_GAP);
    const right = x + BAR_WIDTH;
    const top = MARK_BOTTOM - height;
    const base = MARK_BOTTOM - BASE_RADIUS;
    const r = TOP_RADIUS;
    const b = BASE_RADIUS;
    // A top radius of half the bar is the bar's own width, so the straight run across the top
    // has no length and the two arcs are the whole cap.
    const across = right - r > x + r ? `H${right - r}` : '';
    // Fill is always from the palette, so the guard that compares colours has one thing to read.
    const fill = palette[BAR_TOKENS[index]];
    return `<path fill="${fill}" d="M${x + r} ${top}${across}`
      + `A${r} ${r} 0 0 1 ${right} ${top + r}V${base}`
      + `A${b} ${b} 0 0 1 ${right - b} ${MARK_BOTTOM}H${x + b}`
      + `A${b} ${b} 0 0 1 ${x} ${base}V${top + r}A${r} ${r} 0 0 1 ${x + r} ${top}z"/>`;
  });
};

/**
 * The icon itself. It carries its own provenance, as every generated file here does, so a hand
 * edit is visible at the top of the file rather than only in a diff.
 */
export const faviconSvg = (palette = readPalette()) => `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/favicon.js — do not edit. Edit src/favicon.js and run: npm run favicon -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<title>${site.name}</title>
<rect width="64" height="64" rx="14" fill="${palette.espresso}"/>
${bars(palette).join('\n')}
</svg>
`;
