/**
 * Shared output conventions, imported by every module that emits a file: escaping, safe
 * JSON inside a tag, and the marker stamped into generated artifacts.
 */

/** Escape a value for use as element text or inside a double-quoted attribute. */
export const esc = value => String(value)
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

/**
 * Serialise a value into a data block inside a <script> element — used for the
 * LocalBusiness and FAQ JSON-LD and for the runtime config island. A '<' anywhere in the
 * data could close the tag early, so it is escaped as \u003c, which is still valid JSON.
 */
export const jsonBlock = (type, data, attributes = '') =>
  `<script type="${type}"${attributes}>\n${JSON.stringify(data, null, 2).replace(/</g, '\\u003c')}\n</script>`;

/**
 * Stamped into every generated artifact, each in its own comment syntax. With
 * `npm run check` it makes the generated files self-describing: a hand edit is visible at
 * the top of the file and fails the drift check. One copy, so the wording cannot vary
 * between the page, the stylesheet, and the crawler files.
 */
export const GENERATED_NOTE = 'Generated by src/build.js — do not edit. Edit src/ and run npm run build.';
